export { ConceptSlide } from './ConceptSlide'
export { SplitSlide } from './SplitSlide'
export { ExerciseSlide } from './ExerciseSlide'
export { ParallelSet } from './ParallelSet'
export { SectionSlide } from './SectionSlide'
export { Figure } from './FigureSlide'
export { DefTable } from './DefTable'
export type { DefRow } from './DefTable'
export { StepList } from './StepRow'
export type { Step } from './StepRow'
export { SlideLead, SlideNote } from './SlideLead'
