// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/assignments/sequence-analysis" | "/data" | "/dev-tools" | "/dev-tools/cursor-setup" | "/dev-tools/cursor-setup/cursor-ide" | "/dev-tools/cursor-setup/git" | "/dev-tools/cursor-setup/terminal" | "/dev-tools/cursor-setup/uv-python" | "/labs" | "/labs/1" | "/labs/1/[id]" | "/labs/1/resources" | "/labs/2" | "/labs/2/[id]" | "/labs/3" | "/labs/3/[id]" | "/labs/4" | "/labs/4/[id]" | "/labs/5" | "/labs/6" | "/labs/7" | "/labs/8" | "/labs/cheatsheets" | "/labs/datacamp" | "/lectures/1" | "/lectures/2" | "/lectures/3" | "/lectures/4" | "/lectures/5" | "/lectures/6" | "/lectures/7" | "/lectures/8" | "/notebooks" | "/notebooks/lecture-1" | "/notebooks/lecture-2" | "/notebooks/lecture-3" | "/notebooks/lecture-4" | "/notebooks/lecture-5" | "/practice" | "/projects/depmap-analysis" | "/test-pyodide" | "/under-construction"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/assignments/sequence-analysis": {}
  "/data": {}
  "/dev-tools": {}
  "/dev-tools/cursor-setup": {}
  "/dev-tools/cursor-setup/cursor-ide": {}
  "/dev-tools/cursor-setup/git": {}
  "/dev-tools/cursor-setup/terminal": {}
  "/dev-tools/cursor-setup/uv-python": {}
  "/labs": {}
  "/labs/1": {}
  "/labs/1/[id]": { "id": string; }
  "/labs/1/resources": {}
  "/labs/2": {}
  "/labs/2/[id]": { "id": string; }
  "/labs/3": {}
  "/labs/3/[id]": { "id": string; }
  "/labs/4": {}
  "/labs/4/[id]": { "id": string; }
  "/labs/5": {}
  "/labs/6": {}
  "/labs/7": {}
  "/labs/8": {}
  "/labs/cheatsheets": {}
  "/labs/datacamp": {}
  "/lectures/1": {}
  "/lectures/2": {}
  "/lectures/3": {}
  "/lectures/4": {}
  "/lectures/5": {}
  "/lectures/6": {}
  "/lectures/7": {}
  "/lectures/8": {}
  "/notebooks": {}
  "/notebooks/lecture-1": {}
  "/notebooks/lecture-2": {}
  "/notebooks/lecture-3": {}
  "/notebooks/lecture-4": {}
  "/notebooks/lecture-5": {}
  "/practice": {}
  "/projects/depmap-analysis": {}
  "/test-pyodide": {}
  "/under-construction": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
