// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/assignments/sequence-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assignments/sequence-analysis">> = Specific
  const handler = {} as typeof import("../../app/assignments/sequence-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data">> = Specific
  const handler = {} as typeof import("../../app/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-tools/cursor-setup/cursor-ide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-tools/cursor-setup/cursor-ide">> = Specific
  const handler = {} as typeof import("../../app/dev-tools/cursor-setup/cursor-ide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-tools/cursor-setup/git/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-tools/cursor-setup/git">> = Specific
  const handler = {} as typeof import("../../app/dev-tools/cursor-setup/git/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-tools/cursor-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-tools/cursor-setup">> = Specific
  const handler = {} as typeof import("../../app/dev-tools/cursor-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-tools/cursor-setup/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-tools/cursor-setup/terminal">> = Specific
  const handler = {} as typeof import("../../app/dev-tools/cursor-setup/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-tools/cursor-setup/uv-python/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-tools/cursor-setup/uv-python">> = Specific
  const handler = {} as typeof import("../../app/dev-tools/cursor-setup/uv-python/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-tools">> = Specific
  const handler = {} as typeof import("../../app/dev-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/1/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/1/[id]">> = Specific
  const handler = {} as typeof import("../../app/labs/1/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/1">> = Specific
  const handler = {} as typeof import("../../app/labs/1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/1/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/1/resources">> = Specific
  const handler = {} as typeof import("../../app/labs/1/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/2/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/2/[id]">> = Specific
  const handler = {} as typeof import("../../app/labs/2/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/2">> = Specific
  const handler = {} as typeof import("../../app/labs/2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/3/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/3/[id]">> = Specific
  const handler = {} as typeof import("../../app/labs/3/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/3">> = Specific
  const handler = {} as typeof import("../../app/labs/3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/4/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/4/[id]">> = Specific
  const handler = {} as typeof import("../../app/labs/4/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/4">> = Specific
  const handler = {} as typeof import("../../app/labs/4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/5">> = Specific
  const handler = {} as typeof import("../../app/labs/5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/6">> = Specific
  const handler = {} as typeof import("../../app/labs/6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/7/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/7">> = Specific
  const handler = {} as typeof import("../../app/labs/7/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/8/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/8">> = Specific
  const handler = {} as typeof import("../../app/labs/8/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/cheatsheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/cheatsheets">> = Specific
  const handler = {} as typeof import("../../app/labs/cheatsheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/datacamp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs/datacamp">> = Specific
  const handler = {} as typeof import("../../app/labs/datacamp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs">> = Specific
  const handler = {} as typeof import("../../app/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/1">> = Specific
  const handler = {} as typeof import("../../app/lectures/1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/2">> = Specific
  const handler = {} as typeof import("../../app/lectures/2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/3">> = Specific
  const handler = {} as typeof import("../../app/lectures/3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/4">> = Specific
  const handler = {} as typeof import("../../app/lectures/4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/5">> = Specific
  const handler = {} as typeof import("../../app/lectures/5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/6">> = Specific
  const handler = {} as typeof import("../../app/lectures/6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/7/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/7">> = Specific
  const handler = {} as typeof import("../../app/lectures/7/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lectures/8/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lectures/8">> = Specific
  const handler = {} as typeof import("../../app/lectures/8/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notebooks/lecture-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/lecture-1">> = Specific
  const handler = {} as typeof import("../../app/notebooks/lecture-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notebooks/lecture-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/lecture-2">> = Specific
  const handler = {} as typeof import("../../app/notebooks/lecture-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notebooks/lecture-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/lecture-3">> = Specific
  const handler = {} as typeof import("../../app/notebooks/lecture-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notebooks/lecture-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/lecture-4">> = Specific
  const handler = {} as typeof import("../../app/notebooks/lecture-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notebooks/lecture-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/lecture-5">> = Specific
  const handler = {} as typeof import("../../app/notebooks/lecture-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notebooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks">> = Specific
  const handler = {} as typeof import("../../app/notebooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice">> = Specific
  const handler = {} as typeof import("../../app/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/depmap-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/depmap-analysis">> = Specific
  const handler = {} as typeof import("../../app/projects/depmap-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-pyodide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-pyodide">> = Specific
  const handler = {} as typeof import("../../app/test-pyodide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/under-construction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/under-construction">> = Specific
  const handler = {} as typeof import("../../app/under-construction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
